import { RFPercentage as Percent } from "react-native-responsive-fontsize";
import { Dimensions, StatusBar } from "react-native";

const { width, height } = Dimensions.get("window");
const statusbar = StatusBar.currentHeight;

export const light = {
  colors: {
    primary: "#EA5D60",
    secundary: "#f2f2f2",
    textLigth: "#fff",
    text: "#17171B",
    modal: "#17171b7f",
    gray: "#747476",
    background: "#fafafa",
    inputBackground: "#F2F2F2",
    inputBackgroundPressed: "#e2e2e2",
    typesBackground: {
      water: "#58ABF6",
      steel: "#4C91B2",
      rock: "#D4C294",
      psychic: "#FF6568",
      poison: "#9F6E97",
      normal: "#B5B9C4",
      ice: "#91D8DF",
      ground: "#f78551",
      grass: "#8BBE8A",
      ghost: "#8571BE",
      flying: "#83A2E3",
      fire: "#FFA756",
      fighting: "#EB4971",
      fairy: "#EBA8C3",
      electric: "#F2CB55",
      dragon: "#7383B9",
      dark: "#6F6E78",
      bug: "#8BD674",
    },
    types: {
      water: "#4A90DA",
      steel: "#417D9A",
      rock: "#BAAB82",
      psychic: "#EA5D60",
      poison: "#A552CC",
      normal: "#9DA0AA",
      ice: "#61CEC0",
      ground: "#DD7748",
      grass: "#62B957",
      ghost: "#556AAE",
      flying: "#748FC9",
      fire: "#FD7D24",
      fighting: "#D04164",
      fairy: "#ED6EC7",
      electric: "#EED535",
      dragon: "#0F6AC0",
      dark: "#58575F",
      bug: "#8CB230",
    },
  },
  fontFamily: {
    bold: "bold",
    medium: "medium",
    regular: "regular",
  },
  fontSize: {
    title: `${Percent(4.5)}px`,
    subtitle: `${Percent(3)}px`,
    pokemonName: `${Percent(3)}px`,
    filterTitle: `${Percent(2.2)}px`,
    description: `${Percent(2.5)}px`,
    pokemonNumber: `${Percent(1.8)}px`,
    pokemonType: `${Percent(1.8)}px`,
  },
  border: {
    sm: `${Percent(1)}px`,
    md: `${Percent(2)}px`,
    lg: `${Percent(3)}px`,
    xlg: `${Percent(3.5)}px`,
    xxlg: `${Percent(4)}px`,
    xxxlg: `${Percent(4.5)}px`,
  },
  space: {
    sm: `${Percent(1)}px`,
    md: `${Percent(2)}px`,
    lg: `${Percent(3)}px`,
    xlg: `${Percent(3.5)}px`,
    xxlg: `${Percent(4)}px`,
    xxxlg: `${Percent(5)}px`,
  },
  icons: {
    sm: Percent(1),
    md: Percent(2),
    lg: Percent(3),
    xlg: Percent(3.5),
    xxlg: Percent(4),
    xxxlg: Percent(5),
  },
  screenDimensions: {
    width,
    height,
    statusbar,
  },
};
